### PR TITLE
Add an error when bad load imbalance is detected.

### PR DESCRIPTION
**Pull request by rainwoodman**

### CODE REVIEW

**Comment by adrianbayer** [comment]
Looks good. I changed the error message a little bit so that it's clearer how to fix the error

**Comment by adrianbayer** [comment]
@rainwoodman Actually, maybe this would be "neater" in pm_init instead?

**Comment by adrianbayer** [comment]
For neutrino runs, should we also check that nc / every_ncdm divides?

**Comment by rainwoodman** [comment]
pm_init(): Not really. We shall minimize the occasions of killing the entire application from low level routines like pm_init().
neutrinos: what about check that in lua (hence fastpm-lua can report the error)?

The procmesh check cannot be done in lua (easily) as the procmesh is only available in C and MPI -- we'll have to fake something to check it in lua (and fastpm-lua), and I am not sure the best way to do that.

**Comment by adrianbayer** [comment]
Ok, I see about pm_init().

On neutrinos, I mean do we also have to check
( nc / every_ncdm ) % pm_nproc(fastpm->basepm)[i] != 0 
to avoid load imbalance? Or maybe we need to check the sum of all particles, i.e.
(nc + nc / every) % pm_nproc(fastpm->basepm)[i] != 0?

We could just add it to prepare_ncdm for simplicity, if lua is complicated.

**Comment by rainwoodman** [comment]
Oh that's not needed. The particle load imbalance is derived from the
domain volume imbalance.
The way PFFT works is that if the Nmesh doesn't divide, some ranks will
receive a domain of volume 0. That's the cause of the load imbalance.

This reminds me that as we allow fractional pm_nc_factor checking nc alone
is not enough.
What we really need is that the Nmesh of the PM objects must divide -- aka
we need to add a routine in vpm to validate every possible PM object
against the procmesh.

I will take another look later of the week...

- Yu

**Comment by rainwoodman** [comment]
I ended up adding three separate assertions in solver.c and vpm.c, as we do create several PM objects per solver. 
Please take another look. 
base is for generating the particles. lpt is for LPT and vpm is for the evolution.

Thanks!

**Comment by adrianbayer** [comment]
Yes, it looks good to me! Hopefully the restriction isn't too strict for runs with lpt_nc_factor != pm_nc_factor != 1.

**Comment by rainwoodman** [comment]
When the factors are integers, the larger the factors are, the easier to run, so this won't be too bad, plus we probably won't see very odd fractional B's.

**Pull request merged**
