### PR TITLE
Curvature

### PR DESCRIPTION
**Pull request by adrianbayer**
Allow non-zero Omega_k cosmologies

### CODE REVIEW

**Comment by adrianbayer** [comment]
Will do tests later

**Comment by rainwoodman** [comment]
Shall we merge this?

**Comment by adrianbayer** [comment]
We can merge, but we don't have plans to use this anymore, so I'm not sure if you want the extra parameters in FastPM?

**Comment by rainwoodman** [comment]
The flag is optional, so there is no user facing impact.

If the code is checked in, we avoid this becomes unmergeable in the future. So I'd vote merge.

**Comment by adrianbayer** [comment]
Makes sense!

**Comment by adrianbayer** [comment]
Note there is a bug in dE/da which is fixed in 
https://github.com/fastpm/fastpm/commit/b714897b49cac4907a9c212b341a2ffadb645941

**Pull request merged**
