### PR TITLE
Fix fractional mesh factor implementation

### PR DESCRIPTION
**Pull request by adrianbayer**
Fractional mesh factors were giving same results as integer values.

### CODE REVIEW

**Comment by adrianbayer** [comment]
@rainwoodman I haven't check if there are any more int->doubles needed? I guess we could use float, but I used double because it looks like everything else is a double.

**Comment by adrianbayer** [comment]
@rainwoodman Zhejie tested this and it seems to work now, so I will merge.

**Comment by adrianbayer** [comment]
Based on discussion with Albert, perhaps it would be good to force users to set lpt_nc_factor rather than assume it is 1 if unspecified? Or maybe set lpt_nc_factor=pm_nc_factor by default?

**Comment by rainwoodman** [comment]
It was set to 1 due to a previous bug slowing down the gaussian field
generation. I think that has been fixed.

Typical Gadget simulations lpt_nc_factor is 1. I think in MP-Gadget we
default this to 2 (motivation was related to neutrino accuracy I think).
So, I am OK with either.

**Pull request merged**
